services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file: .env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
